trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  name: TerraformInit
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    commandOptions: '-var access_key=$(access_key)'
    backendType: 'azurerm'
    backendServiceArm: 'prod-00-network-spn'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'myResourceGroup'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'terraformsastore'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'k8.tfstate'
    allowTelemetryCollection: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop-k8s'
#     publishLocation: 'Container'

# - task: TerraformCLI@0
#   name: TerraformApply
#   inputs:
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
#     environmentServiceName: 'prod-00-network-spn'
#     commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'

- task: TerraformCLI@0
  name: TerraformDestroy
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    environmentServiceName: 'prod-00-network-spn'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'