trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    backendType: 'azurerm'
    backendServiceArm: 'prod-00-network-spn'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'cloud-shell-storage-southcentralus'
    backendAzureRmResourceGroupLocation: 'South Central US'
    backendAzureRmStorageAccountName: 'cs710037ffeaa055e81'
    backendAzureRmContainerName: 'tfstatefile'
    backendAzureRmKey: 'k8.tfstate'
    
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    environmentServiceName: 'prod-00-network-spn'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'